### ISSUE TITLE
OS interaction and unicode

### ISSUE THREAD

**Issue by Leont** [doherty/utf8-all#21]
To quote perlunicode:

> One reason that Perl does not attempt to resolve the role of Unicode in these situations is that the answers are highly dependent on the operating system and the file system(s). For example, whether filenames can be in Unicode and in exactly what kind of encoding, is not exactly a portable concept. Similarly for qx and system: how well will the "command-line interface" (and which of them?) handle Unicode?

> * chdir, chmod, chown, chroot, exec, link, lstat, mkdir, rename, rmdir, stat, symlink, truncate, unlink, utime, -X
* %ENV
* glob (aka the <*>)
* open, opendir, sysopen
* qx (aka the backtick operator), system, readdir, readlink

Given we're handling `readdir` now, I'm wondering if we shouldn't also handle most other interfaces with the OS. Not sure we can actually do that for all of these though, some don't overload cleanly.

Also, this may be material for a separate module that's used by utf8::all, instead of being direct part of it.

**Comment by doherty** [comment]
"Fix all the things" is not a very useful bug report.

@HayoBaan: Would you open a bug for each thing or closely-related-set-of-things with a quick description of what's needed? When you're done, please close this issue with a list of the individual issues you created.

**Comment by HayoBaan** [comment]
@doherty Actually from my comment it boils down to just:
 C<readlink> (which is easy to do) and possibly C<qx> / C<``> (though I currently wouldn't know how to replace this with our own version…)
The rest is either done/not necessary or (in the case of C<%ENV>), way to dangerous to implement.

**Comment by HayoBaan** [comment]
So with `readlink` out of the way: if anyone has an idea how to override the default code for the `qx` and backtick operator, I would like to hear it so we can implement these as well.

Also a solution for manipulating %ENV without affecting non `utf8::all` code would be welcome :-)

**Comment by Leont** [comment]
> So with readlink out of the way: if anyone has an idea how to override the default code for the qx and backtick operator, I would like to hear it so we can implement these as well.

That is easy, you can override `readpipe` in much the same way you override readlink and readdir :-)

> Also a solution for manipulating %ENV without affecting non utf8::all code would be welcome :-)

I can think of ways, but none of them is appealing (e.g. ties…)

**Comment by HayoBaan** [comment]
>> So with readlink out of the way: if anyone has an idea how to override the default code for the qx and backtick operator, I would like to hear it so we can implement these as well.
> That is easy, you can override readpipe in much the same way you override readlink and readdir :-)

Awesome, why didn't I think of that earlier? (I do now remember reading about the base of `qx` and the backtick, but couldn't bring it to memory, thanks for reminding me). Perhaps I can have this one done soon too now! :sunglasses:

>> Also a solution for manipulating %ENV without affecting non utf8::all code would be welcome :-)
> I can think of ways, but none of them is appealing (e.g. ties…)
I had been thinking in that direction too, but didn't like the idea either :disappointed:

**Comment by HayoBaan** [comment]
Hmm, there seems to be a little snag when overriding the readpipe; after you've done that, the arguments to qx and the backtick operator aren't interpolated any longer.

Instead of `ls -1 corpus | sort` the argument the overridden `readpipe` gets is `$cmd`.
Is there perhaps some compiler hint that needs to be set to have it interpolate???
(the `readpipe` tests, of course works as expected and does interpolate the arguments).

My test was like the following:
```
#!perl
use strict;
use warnings;
use Test::More 0.96;
use Encode qw/find_encoding FB_CROAK LEAVE_SRC/;

plan skip_all => "Skipped: $^O does not have proper utf-8 file system support"
    if $^O =~ /MSWin32|cygwin|dos|os2/;

mkdir "corpus/\x{307f}\x{304b}\x{3061}\x{3083}\x{3093}"
    or die "Couldn't create directory corpus/\x{307f}\x{304b}\x{3061}\x{3083}\x{3093}: $!"
    unless -d "corpus/\x{307f}\x{304b}\x{3061}\x{3083}\x{3093}";

my $_UTF8 = find_encoding('UTF-8');

plan tests => 3*3;

my $cmd = 'ls -1 corpus | sort';

my $expected = "testfile\n\x{307f}\x{304b}\x{3061}\x{3083}\x{3093}\n";

my $result;
my $utf8_result;

sub test_res {
    my $test = shift;
    my $result = shift;
    my $utf8_result = shift;

    is $utf8_result => $expected, "$test utf8 result should be as expected";
    is $result => $_UTF8->encode($utf8_result, FB_CROAK | LEAVE_SRC), "$test encoded utf8 result matches non-utf8";
    is $_UTF8->decode($result, FB_CROAK | LEAVE_SRC) => $utf8_result, "$test utf8 result matches decoded non-utf8";
}


# readpipe
$result = readpipe($cmd);
{
    use utf8::all;
    $utf8_result = readpipe($cmd);
}
test_res('readpipe', $result, $utf8_result);

# Backtick
$result = `$cmd`;
{
    use utf8::all;
    $utf8_result = `$cmd`;
}
test_res('Backtick', $result, $utf8_result);

# qx
$result = qx{$cmd};
{
    use utf8::all;
    $utf8_result = qx{$cmd};
}
test_res('qx', $result, $utf8_result);
```

**Comment by HayoBaan** [comment]
Ok, guys, I thought I'd do one other test and you're going to laugh now (I know, I did!) :smiley:
It turns out we had been trying to do something that wasn't necessary at all:
Without doing any readpipe override, the results from the `qx`, backtick, and `readpipe` itself already give the expected result (i.e., get decoded/encoded as specified with utf8:all). As it turns out, this is the result of the `use open qw(:encoding(UTF-8) :std);` that we implement…
I'll add this nice fact to the documentation and I will also add the readpipe testcase just to make sure :wink:

So that leaves us with just the evil of `%ENV` :smile:

**Comment by Leont** [comment]
> It turns out we had been trying to do something that wasn't necessary at all

Awesome!

**Comment by doherty** [comment]
Good news! `:D`

I'll open a new issue for %ENV and close this one.

**Comment by Leont** [comment]
> > chdir, chmod, chown, chroot, exec, link, lstat, mkdir, rename, rmdir, stat, symlink, truncate, unlink, utime, -X
> I don't think these need to be changed as they do not return strings and take their input just fine.

That is not quite true. Currently they take internal encoding, they should take character when utf8-all is enabled. It will do the wrong thing (from an u-a perspective) when a string is in octet-mode instead of utf-8 mode.

**Comment by HayoBaan** [comment]
> > > chdir, chmod, chown, chroot, exec, link, lstat, mkdir, rename, rmdir, stat, symlink, truncate, unlink, utime, -X

> > I don't think these need to be changed as they do not return strings and take their input just fine.

> That is not quite true. Currently they take internal encoding, they should take character when utf8-all is enabled. It will do the wrong thing (from an u-a perspective) when a string is in octet-mode instead of utf-8 mode.

Interesting, so far I have not noticed these functions doing anything wrong when you provide them with either an octet or a character string. I'm very much willing to have a go at them though. I'll need a test case (for each case) that breaks if we do not do the conversion though as otherwise I can not test it. Can you help me there?

**Comment by Leont** [comment]
~~~~
use utf8;
use Test::More;

my $utf8 = "Léön";
my $latin1 = $utf8;
utf8::downgrade($latin1, 1);
is($utf8, $latin1);
open my $file, '>', $utf8;
ok -e $utf8;
ok -e $latin1;
unlink $utf8;

done_testing;
~~~~

**Comment by HayoBaan** [comment]
Hi Leon,

Interesting, this indeed fails to find the “latin” version. However, isn't this a **very** unlikely scenario; I mean, when utf8::all is enabled, all strings are assumed to be proper Unicode and when one downgrades deliberately, one should know what one is doing. Wouldn't you agree?

**Comment by Leont** [comment]
> However, isn't this a very unlikely scenario; I mean, when utf8::all is enabled, all strings are assumed to be proper Unicode and when one downgrades deliberately, one should know what one is doing. Wouldn't you agree?

No I don't. When a string comes from a library, you can't make any assumptions about it's internal encoding. This is exactly why we enable for example the `unicode_strings` feature. So either you have to upgrade all strings that came from the outside before using them as a filename, or utf8-all has to safe the day.

**Comment by HayoBaan** [comment]
You have a good point! I'll start to work on it 😃

**Comment by HayoBaan** [comment]
Hi Leon,
this proves to be a bit more involved than thought at first sight. For this to be completely successful, we would need to override _all_ functions that take a file name. This means we also must override ``open`` and perhaps others as well.
Also I don't know how to override the implementation of the filetest operators. A simple overload doesn't seem to work…

**Comment by HayoBaan** [comment]
On a further note, doing this might open a bigger can of worms than we can cope with; for instance, if we override ``stat``, the module ``File::stat`` is likely going to break (depending on the order of using ``utf8::all`` and ``File::stat``). (hmm, this problem might already be there with the functions we _do_ override…)

Hopefully you have a good idea how to solve this (if it is solvable at all…)

**Comment by HayoBaan** [comment]
After some more thinking (and testing some ideas), I have come to the conclusion that we should *NOT* override the functions not returning strings.
A couple of reasons:
- there's basically no end to the functions that we may need to override.
- the more we override, the more we potentially break; ``File::stat`` (and therefore my own ``File::stat::Extra``) is just an example module I know that will “break” if we override ``stat`` or ``lstat``.
- there is indeed no saying in what encoding string parameters are in, it is therefore only safe to assume they are proper unicode characters and leave it up to the user to convert the parameters to a valid (utf8) string.
- I don't think it is at all possible to override the file test operators.

**Comment by Leont** [comment]
Probably this needs to be fixed in core, though an opcode based CPAN module may be a serious option too. Neither is trivial though.

**Comment by HayoBaan** [comment]
> Probably this needs to be fixed in core,
I think core should be updated to better handle UTF-8 encoding, period. I actually think it should be the default (yes, for e.g., Windows provisions need to be made since its filesystem doesn't support utf8). Modules like ``utf8::all``, ``Cwd::utf8``, and ``File::Find::utf8`` shouldn't be necessary anyway.
But given this is quite a radical change, I don't think this will happen soon (if at all in Perl5).

> though an opcode based CPAN module may be a serious option too. Neither is trivial though.
That really sounds like a tough one. Any experience with that?

**Comment by Leont** [comment]
> >  Probably this needs to be fixed in core,
> I think core should be updated to better handle UTF-8 encoding, period. I actually think it should be the default (yes, for e.g., Windows provisions need to be made since its filesystem doesn't support utf8). Modules like utf8::all, Cwd::utf8, and File::Find::utf8 shouldn't be necessary anyway.

> But given this is quite a radical change, I don't think this will happen soon (if at all in Perl5).

I fear it's firmly into "if I don't do it myself it won't happen" territory I suspect :-(

> > though an opcode based CPAN module may be a serious option too. Neither is trivial though.

> That really sounds like a tough one. Any experience with that?

Not yet, but I may try writing a more solid autodie in the near future, there would be many similarities in its implementation.

**Comment by HayoBaan** [comment]
> I fear it's firmly into "if I don't do it myself it won't happen" territory :-(

😞

>> That really sounds like a tough one. Any experience with that?

> Not yet, but I may try writing a more solid autodie in the near future, there would be many similarities in its implementation.

If you need help and/or testing please let me know!
