### ISSUE TITLE
Determine if @ARGV is already decoded

### ISSUE THREAD

**Issue by saulery** [doherty/utf8-all#32]
When Perl (5.20.1) is launched with -CA, @ARGV is already decoded in UTF-8. utf8::all doesn't check and decode systematically. perlrun pod indicates that ${^UNICODE} can be checked for that. -CS and -CD flags may be checked too for fine tuning ?

**Comment by saulery** [comment]
I changed the comment and used shortcut proposed by schwern.

**Comment by HayoBaan** [comment]
That is indeed the solution I used in the code in my pull request :)

**Comment by doherty** [comment]
Fixed by #31 (released to CPAN as 0.016)
