### ISSUE TITLE
More error checking on the utf-8 conversions?

### ISSUE THREAD

**Issue by HayoBaan** [doherty/utf8-all#35]
We currently do not check for conversion errors when encoding/decoding (no, `use warnings FATAL => 'utf8'` does not enforce this!). We also are not making use of an encoding object though this would speed up some of our operations. I suggest we start doing so, and give the user the ability to choose the severity of the conversion errors as well. For instance like I did in my [Cwd::utf8](https://metacpan.org/pod/Cwd::utf8) and [File::Find::utf8](https://metacpan.org/pod/File::Find::utf8) modules:
```
our $UTF8_CHECK = Encode::FB_CROAK; # Die on encoding errors

# UTF-8 Encoding object
my $_UTF8 = Encode::find_encoding('UTF-8');

...

# Enforce LEAVE_SRC
$UTF8_CHECK |= Encode::LEAVE_SRC if $UTF8_CHECK;

$octets = $_UTF8->encode($unicode, $UTF8_CHECK);
$unicode = $_UTF8->decode($octets, $UTF8_CHECK);
```

**Comment by HayoBaan** [comment]
Done

**Comment by Leont** [comment]
I don't think a global variable is the right interface for this for a number of reasons, but most importantly because it's global.

We try to make other properties of this module lexical, so this should also be IMHO.

(I'm also not sure of the value of making decoding errors warnings, but that's a different discussion)

**Comment by Leont** [comment]
Also, the patch is a bit overly enthusiastic in what it tries to encode (e.g. the symbol name argument of readdir)

**Comment by HayoBaan** [comment]
Hi Leon, thank you for taking your time to have a closer look at this. Much appreciated!
I also don't really like the use of a variable to change the behaviour but I couldn't come up with a better approach 😦 The effect is local though; if you use e.g., ``local $utf8::all::UTF8_CHECK = Encode::FB_WARN;``, the effect is confined to the local (lexical) scope. I have reordered the ``utf8_check.t`` test case to confirm this.

As to being overly enthusiastic encoding of the symbol name, you're right. I forgot to add the condition ``$hints->{'utf8::all'}``. I have fixed this. Or do you mean something else as well?

**Comment by Leont** [comment]
> As to being overly enthusiastic encoding of the symbol name, you're right. I forgot to add the condition $hints->{'utf8::all'}. I have fixed this. Or do you mean something else as well?

That wasn't my point, you shouldn't encode it at all. It's useless at best and outright incorrect in others.

Though TBH I'd rather retract the entire change before people start depending on how it currently works. Gives us time to come up with something that's more in line with the rest of the module.

**Comment by HayoBaan** [comment]
>> The effect is local though; if you use e.g., local $utf8::all::UTF8_CHECK = Encode::FB_WARN;, the effect is confined to the local (lexical) scope. I have reordered the utf8_check.t test case to confirm this.
>No it's not. It's confined to the dynamic scope, which is something entirely different: any scope called from the current one is also affected.

Right, that's correct; but wouldn't that be what you want in this case anyway? I mean you wouldn't want a deeper call to bomb out with an error that you sought to suppress?

>> As to being overly enthusiastic encoding of the symbol name, you're right. I forgot to add the condition $hints->{'utf8::all'}. I have fixed this. Or do you mean something else as well?

> That wasn't my point, you shouldn't encode it at all. It's useless at best and outright incorrect in others.
Aaargh, I now see what you are saying: we get passed a _DIRHANDLE_ and that should indeed not be encoded. Doh! 😲

> Though TBH I'd rather retract the entire change before people start depending on how it currently works. Gives us time to come up with something that's more in line with the rest of the module.
Does this refer to the first item or the overzealous encoding? That I will fix and release asap.

**Comment by Leont** [comment]
> Right, that's correct; but wouldn't that be what you want in this case anyway? I mean you wouldn't want a deeper call to bomb out with an error that you sought to suppress?

That module might depend on it bombing out, and now someone else can break that assumption. This is an **action at a distance**, affecting other modules that may depend on invalid data being rejected.

>  Does this refer to the first item or the overzealous encoding? That I will fix and release asap.

I just realized we've been looking at it the wrong way all along. The encoding de facto can't fail because all strings can be expressed as UTF-8 (except if the internal state is a complete mess maybe, which is highly unlikely), so all the effort that's put into making errors non-fatal is moot.

**Comment by HayoBaan** [comment]
So I guess what you're saying is to remove the option altogether :smile:
That's easy, of course. But leaving it in with the default as it is doesn't harm either, does it? Or perhaps from a cleanliness point of view. Anyway, if you think we should get rid of the option, I will remove it.

**Comment by Leont** [comment]
Yes, I think that's the best course of action right now.
