### ISSUE TITLE
scalar filehandles seems not to work when utf8::all adds io-layers

### ISSUE THREAD

**Issue by wanradt** [doherty/utf8-all#37]
Here is little test-case:

    use strict; use warnings; use 5.010; 
    use utf8::all;
    use Data::Printer;
    my $date = localtime;

    open my $fh_scalar, '>', \ my $scalar;
    p $fh_scalar;
    say { $fh_scalar } "test: $date";
    say $scalar;

`$scalar` stays undef while `use utf8::all` adds those utf8-related layers, without it `$scalar` gathers data fine and script prints it out. Seems that for scalar-filehandle those IO-layers are expendable.

**Comment by HayoBaan** [comment]
Interesting! It seems that this is a problem not specifically related to utf8::all, but rather to IO-layers / the open pragma. I didn't have Data::Printer installed, but this little script also shows the problem:
```
perl -E 'use strict; use warnings; use 5.010; 
use open qw{:encoding(UTF-8) :std};
my $date = localtime;

open my $fh_scalar, ">", \ my $scalar;
print $fh_scalar;
say { $fh_scalar } "test: $date";
say $scalar;'
```
Removing the use `open` line gives you the output you expect.

So I'm afraid this is not something that can be solved by `utf8::all` :rage:

**Comment by wanradt** [comment]
So, the right place to give a signal about this bug would be in core (IO::Scalar)?

**Comment by HayoBaan** [comment]
Actually, I think that would be `open.pm`, but more likely the problem is deeper (e.g., in `PerlO::Layer`).

**Comment by Leont** [comment]
> So, the right place to give a signal about this bug would be in core (IO::Scalar)? 

The issue is not in any module but in core itself. Did you perlbug this? I could add it to my todo list but can't promise anything regarding timescales.

**Comment by HayoBaan** [comment]
Hi Leon,
No, I didn't perlbug this and I don't know if @wanradt did.
