### ISSUE TITLE
Respect $ENV{PERL_UNICODE}

### ISSUE THREAD

**Issue by ichesnokov** [doherty/utf8-all#40]
Hi.

The module doesn't work properly when PERL_UNICODE environment variable is set to e.g. 'AS'. In fact it doesn't even install because the tests fail (thanks for writing these tests!).

The module itself and corresponding tests should check that this variable is present and avoid doing unnecessary job of double-encoding.

Thanks.

**Comment by HayoBaan** [comment]
Thanks for reporting this!

While in general I would now advice to not use the PERL_UNICODE environment variable as it can cause unpredicted results when using someone else's code (I learned this the hard way…), I will see what I can do about handling this more gracefully.

**Comment by HayoBaan** [comment]
I have fixed the tests to take the PERL_UNICODE environment variable (and -C flag) into account.

Note: the main code did not need to be changed at all to work properly, just the tests!

This is part of pull request #39, hopefully Mike can merge and release soon.

**Comment by doherty** [comment]
Thanks for taking care of this. I'm on a business trip at the moment, but I
can do a release as soon as I'm back this weekend.

**Comment by doherty** [comment]
Done. Thanks to you both.

**Comment by HayoBaan** [comment]
Hi Mike,

You're welcome! Will you be making a full CPAN release for this too?

Cheers,
Hayo

**Comment by doherty** [comment]
Unless I'm mistaken, the 0.017 release includes all your work from PR #39.

**Comment by HayoBaan** [comment]
Ah, I somehow completely missed the 0.017 release on CPAN 😳
Anyway, everything is there so we're now completely in sync again!

Oh, I think we can close issue #33 as that is now done. Also, issue #17
should now be closable too as all file I/O tests on incompatible systems
are skiped and the directories/files with special characters are no
longer part of the distribution either.

**Comment by doherty** [comment]
Done. Thanks for keeping track of things.
