### ISSUE TITLE
Flag to disable non-lexical things

### ISSUE THREAD

**Issue by tobyink** [doherty/utf8-all#47]
binmode for STDOUT, etc, encoding @ARGV, replacing readdir… all this is non-lexical, which makes utf8::all potentially unsafe to use in Perl modules that aim to be reusable across a wide variety of applications and environments.

It would be nice to be able to do:

    use utf8::all -lexical;

And only get the lexically scoped bits, disabling the other stuff.

**Comment by HayoBaan** [comment]
Good suggestion! I will think about adding this.

**Comment by HayoBaan** [comment]
@tobyink I have just pushed a new version to the repository, could you test this and see if this meets your expectations?

**Comment by tobyink** [comment]
Looks good to me, though actually maybe the readdir, etc stuff could be safe to do, as it does check `%^H`.

**Comment by Leont** [comment]
Quite frankly I think this should be the default when the importing from a package other than `main`

**Comment by HayoBaan** [comment]
@tobyink Re the `^H`, that's true, but why override the functions when later that aspect is not going to be used (ever)? 😉

@Leont Nice! I'll implement that and change the option to "GLOBAL" to allow you to force enabling the global effects even if called from a package other than `main`

**Comment by HayoBaan** [comment]
I implemented the change as proposed by @Leont. Please let me know if there are any issues with this change. If no problems are found, I'll release the new version next week.
Thank you all for your suggestions! 😎
