### ISSUE TITLE
@ARGV still has problems when PERL_UNICODE=A (perl -CA) switch is set

### ISSUE THREAD

**Issue by sjeweler** [doherty/utf8-all#48]
to reproduce:
PERL_UNICODE=A make test
... (other tests work fine)

t/force_global.t ..... 1/? 
#   Failed test '@ARGV as unicode characters instead of utf-8 octets'
#   at t/force_global.t line 18.
#     Structures begin differing at:
#          $got->[0] = 'fÃ¸Ã¸'
#     $expected->[0] = 'føø'
# Looks like you failed 1 test of 7.
t/force_global.t ..... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/7 subtests 

utf8-all-0.023, tested on:
  perl 5, version 20, subversion 2 (v5.20.2) built for x86_64-linux-gnu-thread-multi

No problems if PERL_UNICODE is unset.

Thanks for working on this.

**Comment by HayoBaan** [comment]
Thanks for the report.
The test assumed to be be running in an environment without `-CA` / `PERL_UNICODE=A`. It hard-coded the `@ARGV` to an octet string which it then expected to be  decoded by utf8::all. But when the perl unicode flag is active, this isn't done to prevent decoding `@ARGV` twice... I've adapted the test to skip this part when the flag is enabled.
